package com.bc.springdatajpa.po;
// Generated 2017-8-14 23:57:06 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ImsUser generated by hbm2java
 */
@Entity
@Table(name = "ims_user", catalog = "ims", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class ImsUser implements java.io.Serializable {

    private Long id;
    private String username;
    private String password;
    private String realname;
    private byte usersRole;
    private int department;
    private byte post;
    private String avatar;
    private byte auth;
    private Date gmtCreate;
    private Date gmtUpdate;
    private Date gmtVisit;

    public ImsUser() {
    }
    
    public ImsUser(String username, String password, String realname, byte usersRole, int department, byte post, String avatar, byte auth) {
        this.username = username;
        this.password = password;
        this.realname = realname;
        this.usersRole = usersRole;
        this.department = department;
        this.post = post;
        this.avatar = avatar;
        this.auth = auth;
    }

    public ImsUser(String username, String password, String realname, byte usersRole, int department, byte post, String avatar, byte auth, Date gmtCreate, Date gmtUpdate) {
        this.username = username;
        this.password = password;
        this.realname = realname;
        this.usersRole = usersRole;
        this.department = department;
        this.post = post;
        this.avatar = avatar;
        this.auth = auth;
        this.gmtCreate = gmtCreate;
        this.gmtUpdate = gmtUpdate;
    }

    public ImsUser(String username, String password, String realname, byte usersRole, int department, byte post, String avatar, byte auth, Date gmtCreate, Date gmtUpdate, Date gmtVisit) {
        this.username = username;
        this.password = password;
        this.realname = realname;
        this.usersRole = usersRole;
        this.department = department;
        this.post = post;
        this.avatar = avatar;
        this.auth = auth;
        this.gmtCreate = gmtCreate;
        this.gmtUpdate = gmtUpdate;
        this.gmtVisit = gmtVisit;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "username", unique = true, nullable = false, length = 16)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "realname", nullable = false, length = 20)
    public String getRealname() {
        return this.realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    @Column(name = "users_role", nullable = false)
    public byte getUsersRole() {
        return this.usersRole;
    }

    public void setUsersRole(byte usersRole) {
        this.usersRole = usersRole;
    }

    @Column(name = "department", nullable = false)
    public int getDepartment() {
        return this.department;
    }

    public void setDepartment(int department) {
        this.department = department;
    }

    @Column(name = "post", nullable = false)
    public byte getPost() {
        return this.post;
    }

    public void setPost(byte post) {
        this.post = post;
    }

    @Column(name = "avatar", nullable = false)
    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    @Column(name = "auth", nullable = false)
    public byte getAuth() {
        return this.auth;
    }

    public void setAuth(byte auth) {
        this.auth = auth;
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "gmt_create", length = 19)
    public Date getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "gmt_update", length = 19)
    public Date getGmtUpdate() {
        return this.gmtUpdate;
    }

    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "gmt_visit", length = 19)
    public Date getGmtVisit() {
        return this.gmtVisit;
    }

    public void setGmtVisit(Date gmtVisit) {
        this.gmtVisit = gmtVisit;
    }

}
